application: streiktdiebahn
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /manager.*
  script: manager.py
  login: required

- url: .*
  script: main.py

